# Stage 1: Build
FROM node:alpine AS builder

# Set the working directory
WORKDIR /app

# Install yarn globally
RUN npm install -g yarn

# Copy the package.json and yarn.lock files
COPY package.json yarn.lock ./

# Install the dependencies
RUN yarn install

# Copy the app files
COPY . .

# Build the app
RUN yarn build

# Stage 2: Production
FROM node:alpine

WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/dist /app/dist

# Install serve globally
RUN npm install -g serve

# Expose port 5173
EXPOSE 5173

# Serve the built files
CMD ["serve", "-s", "dist", "-l", "5173"]