export const ERROR_STATUS_CODES: Record<number, string> = {
  400: 'Bad Request. Please try again later.',
  401: 'Unauthorized. Please check your credentials.',
  403: 'Forbidden. You do not have permission to access this resource.',
  404: 'Not Found. The requested resource could not be found.',
  409: 'Conflict. There is a conflict with the request.',
  422: 'Unprocessable Entity. The request could not be processed.',
  500: 'Internal Server Error. Please try again later.',
  502: 'Bad Gateway. Please try again later.',
  503: 'Service Unavailable. Please try again later.',
  504: 'Gateway Timeout. Please try again later.',
  408: 'Request Timeout. Please try again later.',
  413: 'Payload Too Large. The request is too large to process.',
  414: 'URI Too Long. The request URL is too long.',
  429: 'Too Many Requests. Please slow down and try again later.',
  451: 'Unavailable For Legal Reasons. Access to this resource is restricted.',
  1010: 'An unknown error occurred. Please try again later.',
};
